name:                experimenter
version:             0.1.0.0
github:              "schnecki/experimenter"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schneckenreither@uibk.ac.at"
copyright:           "2020 Manuel Schneckenreither"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Perform scientific experiments stored in a DB, and generate reports.
category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schnecki/experimenter#readme>

flags:
  fast:
    description: Disables optimizations
    manual: true
    default: false


dependencies:
  - base >= 4.7 && < 5
  - persistent                    >= 2.0
  - persistent-postgresql         >= 2.1.1
  - persistent-template           >= 2.0
  - lens
  - text
  - cereal
  - monad-logger
  - resource-pool
  - resourcet
  - mtl
  - transformers
  - time
  - mwc-random
  - bytestring
  - aeson
  - esqueleto
  - unliftio-core
  - HaTeX                          >= 3.22.0.0
  - directory
  - process
  - matrix
  - unix
  - hostname
  - deepseq
  - cereal-vector
  - vector
  - containers
  - filepath
  - conduit
  - stm
  - parallel

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Werror
    -Wno-name-shadowing
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -fwarn-tabs
  when:
    - condition: flag(fast)
      then:
        ghc-options: --disable-optimization
      else:
        ghc-options: -O2


tests:
  experimenter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - experimenter
    - foundation
    - hspec
    - QuickCheck
