flags: {}
packages:
- .
- examples
extra-deps: []
# - HaTeX-3.22.2.0@sha256:c491c38724d2c9beac25c5a11c1848e3e1e96bd08b3909bd9711870d3610a594,5407
# resolver: lts-20.11
# resolver: nightly # lts-21.6
# resolver: lts-19.3
# resolver: lts-16.20
resolver: lts-22.17

# Use ghc-9.6.5 or higher
# https://github.com/commercialhaskell/stack/issues/6251
# https://gitlab.haskell.org/ghc/ghc/-/issues/24389
compiler: ghc-9.6.5

