name:                experimenter-examples
version:             0.1.0.0
github:              "schnecki/experimenter"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schneckenreither@uibk.ac.at"
copyright:           "2020 Manuel Schneckenreither"

# Metadata used when publishing your package
synopsis:            Perform scientific experiments stored in a DB, and generate reports.
category:            Experiment examples

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schnecki/experimenter#readme>

flags:
  fast:
    description: Disables optimizations
    manual: true
    default: false


dependencies:
  - base >= 4.7 && < 5
  - persistent                    >= 2.0
  - persistent-postgresql         >= 2.1.1
  - persistent-template           >= 2.0
  - lens
  - text
  - cereal
  - monad-logger
  - resource-pool
  - resourcet
  - mtl
  - transformers
  - time
  - mwc-random
  - bytestring
  - aeson
  - esqueleto
  - unliftio-core
  - HaTeX                          >= 3.22.0.0
  - directory
  - process
  - matrix
  - unix
  - hostname
  - deepseq
  - cereal-vector
  - vector
  - containers
  - filepath
  - conduit
  - stm
  - parallel

executables:
  dice:
    main:                Dice.hs
    other-modules:       []
    source-dirs:         .
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - experimenter
      - random

  dice-stateless:
    main:                DiceStateless.hs
    other-modules:       []
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - experimenter
      - random
